### ISSUE TITLE
Missing -webkit- prefix version for flex direction.

### ISSUE THREAD

**Issue by AltruistEnterprises** [curiositry/flexbox_functions#1]
should probably be this:

box-direction: normal;
box-orient: vertical;
-webkit-flex-direction:column;
flex-direction: column;

**Comment by AltruistEnterprises** [comment]
It may be good to include :
-webkit-box-orient: horizontal;   /\* WebKit */

see: https://developer.mozilla.org/en-US/docs/Web/CSS/box-direction
and: https://developer.mozilla.org/en-US/docs/Web/CSS/box-orient

**Comment by curiositry** [comment]
Good point @GitFr33, thanks. Fixed in 2b924de.
